spring:
  profiles:
    active: pro #选择所使用的环境
---
server:
  port: 8095
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles: pro
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo #这里是配置mybatisPlus进行封装对象的扫描
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jt.mapper: debug

#dubbo配置文件
dubbo:
  scan:
    basePackages: com.jt   #定义包扫描
  application:
    name: provider-order    #定义服务名称 必须添加
  registry:
    address: zookeeper://192.168.188.128:2181?backup=192.168.188.128:2182,192.168.188.128:2183
  protocol:    #协议
    name: dubbo #使用dubbo默认协议
    port: 20882  #端口号唯一
